
name: OSPRay Studio Main CI

# XXX This uses FetchContent on the other components' release packages
# XXX not their devel branches.

# Controls when the workflow will run
on:
  push:
# All branches
#    branches:
#      - '!**release**'
#      - '!master'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:

  ## Build Jobs ##

  ## Linux
  build-centos8:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: centos:8
      cmd: gitlab/build.sh
      artifact-out: build-centos8
      artifact-path: build

  build-ubuntu20-04:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: ubuntu:20.04
      cmd: gitlab/build.sh
      artifact-out: build-ubuntu20-04
      artifact-path: build

  build-ubuntu22-04:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: ubuntu:22.04
      cmd: gitlab/build.sh
      artifact-out: build-ubuntu22-04
      artifact-path: build

  build-arch:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: ospray/docker-images:arch
      cmd: gitlab/build.sh
      artifact-out: build-arch
      artifact-path: build

  build-rocky8-7:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      force-delete: true    # guarantees .gitattributes are respected in working dir
      image: rockylinux:8.7
      cmd: |
        module load cmake/3.25.3
        module load intel/2023.0
        export CC=icx
        export CXX=icpx
        export CXXFLAGS="-fhonor-infinities -fhonor-nans"
        export CFLAGS=$CXXFLAGS
        export LDFLAGS="-static-intel"
        gitlab/build.sh
      artifact-out: build-rocky8-7
      artifact-path: build

  ## MacOS
  build-macos-clang:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/macos.yml@main
    with:
      cmd: |
        gitlab/macos.sh
      artifact-out: build-macos
      artifact-path: build-macos

  ## Windows
  build-windows-msvc15:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      cmd: |
        $env:Python3_ROOT = "N:/packages/apps/python/3.9.7/windows"
        gitlab\win.ps1
      artifact-out: build-windows
      artifact-path: build-win

  build-windows-msvc16:
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/windows.yml@main
    with:
      runs-on: '[ "Windows", "build", "NAS" ]'
      cmd: |
        cmake -L -S . -B build-win-msvc16 -G "Visual Studio 16 2019" -DCMAKE_INSTALL_PREFIX="install"
        cmake --build build-win-msvc16 --parallel $env:NUMBER_OF_PROCESSORS --config Release --target install

  ## Dev Test Jobs
  test-run-rocky8-7:
    needs: build-rocky8-7
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/docker.yml@main
    with:
      image: rockylinux:8.7
      pre-cmd: yum -y install tigervnc-server mesa-libGLU
      cmd: |
        module load intel/2023.0
        build/ospStudio --verify_install
        mkdir build/model-results # in case run-dev tests fail artifacts will still upload
        gitlab/run-dev.sh
        gitlab/run-dev-img-cmp.sh
      artifact-in: build-rocky8-7
      artifact-path: build/model-results build/cert-tests/*
      artifact-out: test-run-rocky8-7
      artifact-on-failure: true

  ### Devel Coverity Job ###
  static-analysis:
    secrets: inherit
    uses: intel-innersource/libraries.devops.renderkit.workflows/.github/workflows/static_analysis.yml@main
    with:
      project: OSPRay Studio
      prebuild: >
        module load cmake/3.25.3 &&
        cmake -L -S . -B build -DENABLE_OPENIMAGEIO=OFF -DENABLE_OPENVDB=OFF -DENABLE_EXR=OFF
      build: cmake --build build
